"""
전업투자자가 사용하는 플랫폼 리스트 Excel 생성.
2 시트: 한국 / 미국
Columns: 번호 | 카테고리 | 플랫폼 | 핵심기능 | 상황별 사용법 | 유료/무료 | 링크
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ───────────────────────────────────────────────────────────────────────
# 한국 데이터 — 실제 전업투자자 풀 스택
# ───────────────────────────────────────────────────────────────────────
KR = [
    # 카테고리, 플랫폼, 핵심기능, 상황별 사용법, 유료/무료, 링크
    # 1. HTS / MTS — 증권사 주문 플랫폼
    ("HTS/MTS (매매 주문)", "키움증권 영웅문4 / 영웅문S",
     "국내 1위 HTS, 주문체결 속도·OpenAPI+ 무료 제공",
     "단타·스캘핑 1순위. OpenAPI+로 개인 자동매داء 구축. 거래량 많은 국내 개인투자자 표준.",
     "무료(계좌)", "https://www.kiwoom.com"),
    ("HTS/MTS (매매 주문)", "미래에셋증권 M-STOCK",
     "해외주식 통합, 퇴직연금 연동",
     "서학개미 유저 1순위. 해외주식 원화결제 편의. 연금·ISA 장기자금 운용 병행자 선호.",
     "무료(계좌)", "https://securities.miraeasset.com"),
    ("HTS/MTS (매매 주문)", "한국투자증권 eFriend Plus / KIS Developers",
     "KIS OpenAPI 정식 제공, 개인 자동매매 API 친화",
     "파이썬 기반 자동매매·퀀트 구축. 개인 API 토큰 + 실시간 시세 무료. 본 프로젝트도 KIS 기반.",
     "무료(계좌)", "https://apiportal.koreainvestment.com"),
    ("HTS/MTS (매매 주문)", "삼성증권 POP / mPOP",
     "리서치 리포트 품질, 프리미엄 고객 서비스",
     "대형 자산 투자자·중장기 투자자. 자체 리서치 자료 신뢰도.",
     "무료(계좌)", "https://www.samsungpop.com"),
    ("HTS/MTS (매매 주문)", "NH투자증권 QV / NH MTS",
     "ETF·퇴직연금 라인업, 파생상품",
     "ETF 포트폴리오 운용자. IRP/연금저축 장기 플랜.",
     "무료(계좌)", "https://www.nhqv.com"),
    ("HTS/MTS (매매 주문)", "대신증권 크레온 (Cybos Plus)",
     "COM 기반 퀀트 자동매매 개인 표준",
     "Windows 퀀트 개발자의 사실상 표준. 백테스트→실전 자동매매 연결.",
     "무료(계좌)", "https://www.creontrade.com"),
    ("HTS/MTS (매매 주문)", "이베스트투자증권 이베스트",
     "파생·ELW 특화, 선물옵션 거래비용 낮음",
     "파생 트레이더, 단기 레버리지 전략.",
     "무료(계좌)", "https://www.ebestsec.co.kr"),
    ("HTS/MTS (매매 주문)", "신한투자증권 SOL",
     "차트 UX 강점, 간편 MTS",
     "모바일 중심 차트 분석.",
     "무료(계좌)", "https://www.shinhansec.com"),
    ("HTS/MTS (매매 주문)", "KB증권 마블 (M-able)",
     "전통 은행계 신뢰, 연금 연계",
     "은행계 안정성 선호 투자자.",
     "무료(계좌)", "https://www.kbsec.com"),
    ("HTS/MTS (매매 주문)", "토스증권",
     "MZ세대 직관 UX, 낮은 환율수수료",
     "소액 분산·해외주식 저마찰. 장기 적립식 스타일.",
     "무료(계좌)", "https://tossinvest.com"),
    ("HTS/MTS (매매 주문)", "카카오페이증권",
     "소액·동전투자·카카오페이 연동",
     "투자 입문자, 소액 자동투자.",
     "무료(계좌)", "https://securities.kakaopay.com"),
    ("HTS/MTS (매매 주문)", "하나증권 1Q Pro",
     "1Q 패밀리 연계, 해외주식 원화결제",
     "하나금융 고객 통합 뷰.",
     "무료(계좌)", "https://www.hanaw.com"),

    # 2. 실시간 시세·국민 포털
    ("실시간 시세 포털", "네이버 증권",
     "국민 종목 페이지, 실시간 호가·토론실 원조",
     "거의 모든 한국 투자자가 거쳐가는 기본 시세 플랫폼. 종목 토론실은 실시간 여론 파악.",
     "무료", "https://finance.naver.com"),
    ("실시간 시세 포털", "다음 금융",
     "카카오계 시세 포털, 서브 체크용",
     "네이버 백업·교차검증.",
     "무료", "https://finance.daum.net"),
    ("실시간 시세 포털", "팍스넷",
     "종목토론·속보, 개미 여론·루머 모니터",
     "네이버 토론실 보완. 펌프&덤프 시그널 관측.",
     "무료", "https://www.paxnet.co.kr"),
    ("실시간 시세 포털", "인포스탁",
     "종목 속보·재료 중심 뉴스",
     "테마·재료 이슈 빠른 포착. 단기 모멘텀 트레이더.",
     "무료+유료", "https://www.infostock.co.kr"),
    ("실시간 시세 포털", "인베스팅닷컴 한국",
     "글로벌 지표·경제캘린더·뉴스",
     "해외 선물·환율·경제지표 한 곳 체크. 경제캘린더 표준.",
     "무료+유료", "https://kr.investing.com"),
    ("실시간 시세 포털", "이데일리 마켓포인트",
     "실시간 시세 + 증권 뉴스 통합",
     "뉴스·시세 병행 체크.",
     "무료", "https://marketpoint.edaily.co.kr"),
    ("실시간 시세 포털", "아이투자",
     "가치투자·재무 스크리너",
     "가치투자 스타일 종목 발굴.",
     "무료+유료", "https://www.itooza.com"),

    # 3. 공시 · 기업정보 (코어)
    ("공시·기업정보", "DART 전자공시시스템",
     "금융감독원 공식 공시, OpenAPI 무료 제공",
     "기업 공시 1순위. 실적·증자·대주주 변동 전부 여기. 모든 개인 퀀트 시작점.",
     "무료(API 무료)", "https://dart.fss.or.kr"),
    ("공시·기업정보", "KIND (KRX)",
     "한국거래소 공식 공시·시장조치",
     "거래정지·관리종목 지정 등 거래소 레벨 이슈.",
     "무료", "https://kind.krx.co.kr"),
    ("공시·기업정보", "FnGuide Company Guide",
     "기업분석 재무 표준, 증권사 탑재",
     "기업 5년 재무 한눈에. 증권사 HTS 내에 탑재되어 있는 경우 많음.",
     "유료(증권사 연동 무료)", "https://comp.fnguide.com"),
    ("공시·기업정보", "에프앤가이드 컨센서스",
     "애널리스트 추정치·컨센서스",
     "실적 서프라이즈 추적. 어닝 시즌 필수.",
     "유료", "https://www.fnguide.com"),
    ("공시·기업정보", "한경컨센서스",
     "무료 리포트 집계 — 증권사 보고서 PDF",
     "증권사 리서치 리포트 무료 다운로드. 타깃 프라이스·투자의견 확인.",
     "무료", "https://consensus.hankyung.com"),
    ("공시·기업정보", "세이브로 (한국예탁결제원)",
     "주주명부·배당일정·주식병합",
     "배당 기준일·실권주·유상증자 일정 확인.",
     "무료", "https://seibro.or.kr"),

    # 4. 뉴스·속보·경제지
    ("뉴스·속보", "한국경제 (한경)",
     "증권 1면, 기업·정책·시장 종합",
     "아침 브리핑 1순위. 유료 구독시 1면 헤드라인 프리미엄.",
     "무료+유료", "https://www.hankyung.com"),
    ("뉴스·속보", "매일경제 (매경)",
     "경제·증권 종합지",
     "한경 교차검증. 기업·산업 보도.",
     "무료+유료", "https://www.mk.co.kr"),
    ("뉴스·속보", "서울경제",
     "증권·부동산·금융 깊이",
     "부동산·금융 토픽 강점.",
     "무료+유료", "https://www.sedaily.com"),
    ("뉴스·속보", "머니투데이 / MT Chem",
     "바이오·테크 전문, 스타트업",
     "바이오·테크 섹터 전문 기자 있음.",
     "무료+유료", "https://www.mt.co.kr"),
    ("뉴스·속보", "이데일리",
     "증권·경제 종합, 마켓포인트",
     "시세와 뉴스 통합 체크.",
     "무료+유료", "https://www.edaily.co.kr"),
    ("뉴스·속보", "연합인포맥스",
     "채권·외환·매크로 프로 전문지",
     "채권 금리·외환 변동, 한국은행 정책 관련 핵심. 인스티튜셔널 표준.",
     "유료", "https://www.einfomax.co.kr"),
    ("뉴스·속보", "뉴스핌",
     "속보·산업 깊이, 경제 심층",
     "속보 + 산업 분석.",
     "무료+유료", "https://www.newspim.com"),
    ("뉴스·속보", "블로터",
     "IT·테크·스타트업 전문",
     "테크 섹터 뉴스 소스.",
     "무료", "https://www.bloter.net"),
    ("뉴스·속보", "조선비즈",
     "조선일보계 경제, 기업 심층",
     "보수 경제 관점 체크.",
     "무료+유료", "https://biz.chosun.com"),
    ("뉴스·속보", "연합뉴스",
     "공식 속보 통신사",
     "거시·정치·정책 속보 1차 소스.",
     "무료", "https://www.yna.co.kr"),

    # 5. 커뮤니티·게시판
    ("커뮤니티·여론", "네이버 종목토론실",
     "종목별 실시간 여론·루머",
     "개미 심리 파악 1순위. 과열·패닉 시그널 관측용 (신뢰도는 0에 가까움).",
     "무료", "https://finance.naver.com/item/board.naver"),
    ("커뮤니티·여론", "디시인사이드 주식갤러리",
     "날것의 개미 여론·미시적 정보",
     "날것 개미 심리 + 간혹 알짜 정보. 노이즈 대다수.",
     "무료", "https://gall.dcinside.com/board/lists/?id=stock_new2"),
    ("커뮤니티·여론", "팍스넷 종목토론",
     "네이버 토론실 대안",
     "네이버 토론실 대체·교차검증.",
     "무료", "https://www.paxnet.co.kr/tbbs"),
    ("커뮤니티·여론", "MLBPark 주식게시판",
     "스포츠커뮤니티 파생 주식게시판",
     "타 커뮤니티보다 덜 시끄러움. 장기투자·미국주식 비중.",
     "무료", "https://mlbpark.donga.com/mp/b.php?b=bullpen2"),
    ("커뮤니티·여론", "블라인드 주식 탭",
     "직장인 익명 주식 토론",
     "회사 내부자 관점 루머·산업 트렌드 (검증 필수).",
     "무료(회사메일 인증)", "https://www.teamblind.com"),
    ("커뮤니티·여론", "더쿠 재테크 게시판",
     "여성 중심 재테크·투자 토론",
     "이성적 장기 투자 성향 강함.",
     "무료", "https://theqoo.net"),
    ("커뮤니티·여론", "클리앙 주식/재테크 게시판",
     "IT 성향 커뮤니티, 장기투자 성향",
     "미국주식·ETF 장투 성향 강함.",
     "무료", "https://www.clien.net"),

    # 6. 유튜브 · 경제 미디어
    ("유튜브·경제미디어", "삼프로TV",
     "한국 최대 경제·투자 유튜브",
     "아침·저녁 라이브. 김동환·이진우·정영진·권순우 합류. 시장 개요 표준.",
     "무료(슈퍼챗 유료)", "https://www.youtube.com/@3protv"),
    ("유튜브·경제미디어", "슈카월드",
     "거시경제 엔터, 역사·정책 통합 해설",
     "거시·정치·국제정세. 토픽 백그라운드 학습.",
     "무료", "https://www.youtube.com/@syukaworld"),
    ("유튜브·경제미디어", "박곰희TV",
     "개별 종목·미국주식 해설",
     "종목 분석 깊이. 주식 초심자~중급자.",
     "무료", "https://www.youtube.com/@parkgomhi"),
    ("유튜브·경제미디어", "김작가TV",
     "CEO 인터뷰·투자 인사이트",
     "게스트 인터뷰 중심. 산업 인사이트.",
     "무료", "https://www.youtube.com/@_kimjakka"),
    ("유튜브·경제미디어", "언더스탠딩",
     "기자 3인 경제 해설",
     "뉴스 밑바닥 해설. 장기투자자용 배경지식.",
     "무료", "https://www.youtube.com/@understanding."),
    ("유튜브·경제미디어", "신과함께",
     "명함 CEO 인터뷰·심층",
     "산업·기업 딥다이브.",
     "무료", "https://www.youtube.com/@withgod1130"),
    ("유튜브·경제미디어", "체슬리TV (박세익)",
     "실전 전략·매매 관점",
     "실전 투자자 관점 + 기관 시선.",
     "무료", "https://www.youtube.com/@chesley_tv"),
    ("유튜브·경제미디어", "이효석아카데미",
     "기관 애널리스트 출신 실전 전략",
     "퀀트·매크로·기관 시선.",
     "무료(유료 멤버십)", "https://www.youtube.com/@leehyoseok"),
    ("유튜브·경제미디어", "염승환 이사 (이베스트)",
     "어닝 시즌 실적 리뷰",
     "실적 시즌 종목별 리뷰 표준.",
     "무료", "https://www.youtube.com/@yeom"),
    ("유튜브·경제미디어", "홍춘욱 박사",
     "매크로·달러·금리 해설",
     "환율·채권·매크로 프레임 학습.",
     "무료", "https://www.youtube.com/@honghousehold"),
    ("유튜브·경제미디어", "한경 와우넷 WOWTV",
     "한경계 방송, 전문가 패널",
     "방송 인터뷰·종목 리뷰.",
     "무료", "https://wowtv.co.kr"),

    # 7. 데이터·API (개발자·퀀트)
    ("데이터·API", "DART OpenAPI",
     "공시 데이터 무료 API",
     "기업 공시 데이터 긁기 1순위. 재무제표·사업보고서 크롤링.",
     "무료", "https://opendart.fss.or.kr"),
    ("데이터·API", "KRX 정보데이터시스템",
     "거래소 원데이터 — 종가·수급·프로그램매매",
     "일일 시장 데이터 다운로드. 외국인·기관 수급 원본.",
     "무료", "http://data.krx.co.kr"),
    ("데이터·API", "한국은행 ECOS API",
     "거시경제지표 API (GDP·CPI·환율·금리)",
     "경제지표 시계열 수집. 백테스트 매크로 팩터.",
     "무료(키 발급)", "https://ecos.bok.or.kr/api"),
    ("데이터·API", "KIS Developers (한투)",
     "개인 실시간 시세·주문 API",
     "개인이 받을 수 있는 국내 최상급 실시간 API. 본 프로젝트 채택.",
     "무료(계좌)", "https://apiportal.koreainvestment.com"),
    ("데이터·API", "키움 OpenAPI+",
     "Windows COM 기반 자동매매 API",
     "국내 자동매매 표준 (Windows 한정).",
     "무료(계좌)", "https://www3.kiwoom.com/nkw.templateFrameSet.do?m=m1408000000"),
    ("데이터·API", "FinanceDataReader",
     "한국 + 글로벌 가격 Python 라이브러리",
     "pip 설치로 KOSPI/KOSDAQ/미국 과거가 일봉 수집.",
     "무료(오픈소스)", "https://github.com/financedata-org/FinanceDataReader"),
    ("데이터·API", "pykrx",
     "KRX 크롤링 Python",
     "KRX 페이지 크롤링. 시가총액·수급·지수 데이터.",
     "무료(오픈소스)", "https://github.com/sharebook-kr/pykrx"),
    ("데이터·API", "통계청 KOSIS",
     "국가통계 포털 — 인구·산업·물가",
     "매크로·정책 팩터 데이터.",
     "무료", "https://kosis.kr"),
    ("데이터·API", "퀀트킹 (Quantking)",
     "퀀트 전략 백테스트·스크리너",
     "코딩 없이 팩터 백테스트. 유료 구독.",
     "유료", "https://www.quantking.net"),
    ("데이터·API", "퀀티랩 (Quantylab)",
     "커뮤니티·퀀트 교육·백테스트",
     "퀀트 입문 교육·툴.",
     "유료", "https://www.quantylab.com"),

    # 8. 차트·기술적 분석
    ("차트·기술분석", "TradingView",
     "글로벌 차트 1위, 한국 종목 지원",
     "차트 공유·pine script 전략. 한국 투자자도 보조 차트로 표준 채택.",
     "무료+유료", "https://www.tradingview.com"),
    ("차트·기술분석", "Investar 차트",
     "한국 차트 분석 전문 SW",
     "정교한 기술적 분석·백테스트.",
     "유료", "https://www.investar.co.kr"),
    ("차트·기술분석", "증권사 HTS 차트",
     "각 HTS 내장 차트",
     "주문창 일체화 차트. 단타 실전용.",
     "무료(계좌)", "-"),

    # 9. 해외주식 (한국계 증권사)
    ("해외주식 (한국계)", "키움 영웅문 글로벌",
     "키움 해외주식 통합",
     "키움 기존 사용자 해외주식 확장.",
     "무료(계좌)", "https://www.kiwoom.com"),
    ("해외주식 (한국계)", "미래에셋 해외주식 (M-Global)",
     "해외주식 점유율 1위, 광범위 시장",
     "미국·홍콩·중국·일본·유럽 통합. 달러RP 연계.",
     "무료(계좌)", "https://securities.miraeasset.com"),
    ("해외주식 (한국계)", "삼성증권 해외주식",
     "해외 리서치 강점",
     "미국 리서치 품질. 대형주 장기 투자.",
     "무료(계좌)", "https://www.samsungpop.com"),
    ("해외주식 (한국계)", "토스증권 해외주식",
     "환전 수수료 최저 수준",
     "단기·소액 미국주식. 거래비용 최소화.",
     "무료(계좌)", "https://tossinvest.com"),
    ("해외주식 (한국계)", "카카오페이증권 해외주식",
     "소액 분할매수·동전투자",
     "월급 적립식 미국 ETF.",
     "무료(계좌)", "https://securities.kakaopay.com"),

    # 10. 세금·백오피스
    ("세금·백오피스", "국세청 홈택스",
     "양도세·배당소득세 신고",
     "해외주식 양도세 250만원 공제·22% 세율. 매년 5월 신고.",
     "무료", "https://www.hometax.go.kr"),
    ("세금·백오피스", "세이브로 (예탁결제원)",
     "배당일정·주주명부·실권주",
     "배당 기준일 확인·ISIN 조회.",
     "무료", "https://seibro.or.kr"),

    # 11. 매크로·경제지표
    ("매크로·경제지표", "한국은행 ECOS",
     "한국 경제지표 총본산",
     "GDP·CPI·기준금리·환율·수출입. 매크로 팩터 원본.",
     "무료", "https://ecos.bok.or.kr"),
    ("매크로·경제지표", "통계청 KOSIS",
     "국가통계 포털",
     "산업·인구·물가 통계.",
     "무료", "https://kosis.kr"),
    ("매크로·경제지표", "기획재정부",
     "정책·재정·세제 발표",
     "정책 변화 1차 소스.",
     "무료", "https://www.moef.go.kr"),
    ("매크로·경제지표", "KDI 경제동향",
     "국책 싱크탱크 월간 경제 분석",
     "분기 경제 전망·업황 평가.",
     "무료", "https://www.kdi.re.kr"),

    # 12. 텔레그램·리딩 (주의 필요)
    ("텔레그램·리딩방", "한경/매경 공식 텔레그램 속보",
     "언론사 공식 속보 채널",
     "장중 속보 푸시. 리딩방 아닌 뉴스 스트림.",
     "무료", "https://telegram.org"),
    ("텔레그램·리딩방", "여의도 리딩방 (일반)",
     "유료 리딩 서비스 (법적 회색지대)",
     "대부분 과장·사기 위험. 법령 위반 소지 큼 — 참고만.",
     "유료(주의)", "-"),

    # 13. 기타 툴·플러그인
    ("기타 툴", "Excel + 한경컨센서스 Add-in",
     "재무 데이터 엑셀 자동연동",
     "재무제표 엑셀 모델링.",
     "유료", "https://consensus.hankyung.com"),
    ("기타 툴", "네이버 클로바X / ChatGPT",
     "뉴스·리포트 요약, 종목 Q&A",
     "리서치 리포트 요약·모델 설명 요청.",
     "무료+유료", "https://chat.openai.com"),
]

# ───────────────────────────────────────────────────────────────────────
# 미국 데이터 — Pro trader 풀 스택
# ───────────────────────────────────────────────────────────────────────
US = [
    # 1. Broker / Trading platforms
    ("Broker / Trading", "Interactive Brokers (IBKR)",
     "Pro/semi-pro 글로벌 표준, 최다 시장 커버",
     "전업 트레이더·퀀트 1순위. 150+ 시장, 낮은 수수료, IBKR API (Python, Java). 헤지펀드·RIA 기본.",
     "무료(계좌)", "https://www.interactivebrokers.com"),
    ("Broker / Trading", "Charles Schwab / thinkorswim",
     "thinkorswim 인수, 옵션·파생 프로 플랫폼",
     "옵션 트레이더 1순위. Thinkscript 스크립팅. 리테일·프로 모두 커버.",
     "무료(계좌)", "https://www.schwab.com"),
    ("Broker / Trading", "Fidelity Active Trader Pro",
     "대형 리테일, 액티브 트레이딩 + 연금 연동",
     "IRA·401k 장기투자 + 액티브 트레이딩 병행.",
     "무료(계좌)", "https://www.fidelity.com"),
    ("Broker / Trading", "E*TRADE Power E*TRADE",
     "옵션 특화 UI, Morgan Stanley 편입",
     "옵션 초중급자에 인기.",
     "무료(계좌)", "https://us.etrade.com"),
    ("Broker / Trading", "TradeStation",
     "시스템 트레이딩 EasyLanguage",
     "시스템 트레이더·알고 개인 표준.",
     "무료(계좌)", "https://www.tradestation.com"),
    ("Broker / Trading", "Lightspeed Trading",
     "초고속 주문·데이 트레이더 전문",
     "데이 트레이더·스캘퍼. DMA·ECN 직접 라우팅.",
     "유료(월 플랫폼)", "https://www.lightspeed.com"),
    ("Broker / Trading", "Cobra Trading",
     "숏 locate 강점, 데이트레이더 PDT 우회 구조",
     "숏 스퀴즈·파낼·데이트레이더 전용.",
     "유료(월 플랫폼)", "https://www.cobratrading.com"),
    ("Broker / Trading", "Tastytrade",
     "옵션 전문, 교육+브로커 통합",
     "옵션 커뮤니티·교육 결합. 세타·쇼트 프리미엄 중심.",
     "무료(계좌)", "https://tastytrade.com"),
    ("Broker / Trading", "Webull",
     "리테일 무료, 프리마켓 강점",
     "프리마켓·애프터 확장 세션. 모바일 중심.",
     "무료(계좌)", "https://www.webull.com"),
    ("Broker / Trading", "Robinhood",
     "MZ 리테일 무료 주식·옵션·크립토",
     "리테일 트레이더 입문. WSB 밈주 트레이드.",
     "무료(계좌)", "https://robinhood.com"),
    ("Broker / Trading", "Merrill Edge",
     "Bank of America 연동, 프리미어 고객",
     "BoA 통합 자산관리.",
     "무료(계좌)", "https://www.merrilledge.com"),
    ("Broker / Trading", "Public.com",
     "소셜 투자, 티팁(팁) 모델",
     "커뮤니티 드리븐 리테일.",
     "무료(계좌)", "https://public.com"),

    # 2. Charts / Technical Analysis
    ("Charts / Technical", "TradingView",
     "세계 1위 차트, Pine Script 전략",
     "차트·스크린·알람·커뮤니티 통합. 모든 레벨 트레이더 필수. 한국 투자자도 대다수 사용.",
     "무료+유료", "https://www.tradingview.com"),
    ("Charts / Technical", "thinkorswim",
     "Schwab 소속, 옵션 전략 비주얼 최강",
     "옵션 체인·확률콘 시각화·백테스트.",
     "무료(Schwab 계좌)", "https://www.schwab.com/thinkorswim"),
    ("Charts / Technical", "StockCharts.com",
     "기술적 분석 교과서, RRG·시즌패턴",
     "기술적 분석 학습·중급자용.",
     "유료", "https://stockcharts.com"),
    ("Charts / Technical", "Finviz",
     "Heatmap·무료 스크리너 1위",
     "시장 한눈에 + 펀더멘털 스크리너. 무료로 접근성 극대화.",
     "무료+유료", "https://finviz.com"),
    ("Charts / Technical", "NinjaTrader",
     "선물 트레이더 표준, C# 스크립팅",
     "선물·고빈도 전략 백테스트.",
     "무료+유료", "https://ninjatrader.com"),
    ("Charts / Technical", "eSignal",
     "프로페셔널 차트, 시장 데이터 깊이",
     "인스티튜셔널·RIA.",
     "유료", "https://www.esignal.com"),
    ("Charts / Technical", "Trade Ideas",
     "AI 기반 실시간 스캐너",
     "AI 패턴 감지 스캐너. 데이 트레이더.",
     "유료", "https://www.trade-ideas.com"),
    ("Charts / Technical", "MetaStock",
     "전통 테크니컬 분석 SW",
     "장기 기술분석가.",
     "유료", "https://www.metastock.com"),

    # 3. Fundamentals / Research (Pro & Retail)
    ("Fundamentals / Research", "Bloomberg Terminal",
     "Pro 표준, 뉴스+데이터+채팅 통합 ($24K/년)",
     "헤지펀드·IB·뮤추얼펀드 표준 단말기. 분석·메신저·뉴스·데이터 원스톱.",
     "유료 ($24K/년)", "https://www.bloomberg.com/professional"),
    ("Fundamentals / Research", "Refinitiv Eikon / Workspace",
     "Bloomberg 경쟁, LSEG 인수",
     "IB·채권·FX 기관 표준 대체.",
     "유료", "https://www.lseg.com/en/data-analytics"),
    ("Fundamentals / Research", "FactSet",
     "기관 리서치·모델링",
     "뮤추얼펀드·RIA 모델링 표준.",
     "유료", "https://www.factset.com"),
    ("Fundamentals / Research", "S&P Capital IQ Pro",
     "기관 M&A·크레딧·프라이빗 커버",
     "IB·PE·컨설팅 데이터 1순위.",
     "유료", "https://www.spglobal.com/marketintelligence"),
    ("Fundamentals / Research", "Koyfin",
     "Bloomberg 저가형, 스타트업 성장",
     "프로급 UI·단축키. 개인~소형 펀드 저비용 대안.",
     "무료+유료", "https://www.koyfin.com"),
    ("Fundamentals / Research", "Morningstar",
     "펀드·ETF 레이팅 표준",
     "Mutual fund·ETF 평가·Moat 분석.",
     "무료+유료", "https://www.morningstar.com"),
    ("Fundamentals / Research", "YCharts",
     "재무 차트·경제지표 통합",
     "RIA·포트폴리오 매니저.",
     "유료", "https://ycharts.com"),
    ("Fundamentals / Research", "Simply Wall St",
     "비주얼 기업분석 Snowflake 그래프",
     "개인 투자자 UX 친화 펀더멘털.",
     "무료+유료", "https://simplywall.st"),
    ("Fundamentals / Research", "Stock Analysis",
     "무료 재무 요약·10년 히스토리",
     "무료로 최고 수준 재무 요약. 체크용 즐겨찾기.",
     "무료+유료", "https://stockanalysis.com"),
    ("Fundamentals / Research", "Tikr Terminal",
     "Bloomberg 저가 대안 (30+년 재무)",
     "개인 장기 투자자·밸류 투자자.",
     "무료+유료", "https://www.tikr.com"),
    ("Fundamentals / Research", "Macrotrends",
     "무료 30년 재무 차트",
     "장기 재무 트렌드 체크 무료.",
     "무료+유료", "https://www.macrotrends.net"),
    ("Fundamentals / Research", "Finbox",
     "밸류에이션 모델·DCF",
     "DCF·상대가치 모델 빠른 비교.",
     "무료+유료", "https://finbox.com"),
    ("Fundamentals / Research", "GuruFocus",
     "구루 포트폴리오 추적 + Screener",
     "버핏·파브라이·왓사 등 포트폴리오 팔로우.",
     "무료+유료", "https://www.gurufocus.com"),
    ("Fundamentals / Research", "Wisesheets (Excel)",
     "Excel 애드인 재무 데이터 자동 연결",
     "엑셀 모델링 자동화. 밸류에이션 워크플로우.",
     "유료", "https://wisesheets.io"),
    ("Fundamentals / Research", "Seeking Alpha (Pro)",
     "아티클·애널리스트·실적 추정",
     "롱 thesis 수집·커뮤니티 분석. 컨센서스 보완.",
     "무료+유료", "https://seekingalpha.com"),
    ("Fundamentals / Research", "Stratosphere.io",
     "Tikr 대안, 캐나다 스타트업",
     "저가 Bloomberg 대체.",
     "무료+유료", "https://stratosphere.io"),

    # 4. News / Wire Services
    ("News / Wire", "Wall Street Journal (WSJ)",
     "미 경제 1면 표준",
     "매일 아침 1면. 정책·기업·경제 심층.",
     "유료(구독)", "https://www.wsj.com"),
    ("News / Wire", "Financial Times (FT)",
     "글로벌 경제·정책, 유럽 시각",
     "글로벌 매크로·정책 시선.",
     "유료(구독)", "https://www.ft.com"),
    ("News / Wire", "Barron's",
     "주간 심층분석 + 종목 아이디어",
     "주말 투자 아이디어·롱폼.",
     "유료(구독)", "https://www.barrons.com"),
    ("News / Wire", "Bloomberg News",
     "실시간 글로벌 금융 뉴스",
     "Terminal 연동 + 무료 일부.",
     "무료+유료", "https://www.bloomberg.com"),
    ("News / Wire", "Reuters",
     "통신사 + 금융 뉴스",
     "속보·매크로·지정학.",
     "무료+유료", "https://www.reuters.com"),
    ("News / Wire", "CNBC",
     "TV + 실시간 금융 뉴스",
     "장중 실시간 + 경제 방송.",
     "무료+유료", "https://www.cnbc.com"),
    ("News / Wire", "MarketWatch",
     "Dow Jones계 무료 금융 뉴스",
     "무료 금융뉴스 표준.",
     "무료", "https://www.marketwatch.com"),
    ("News / Wire", "Yahoo Finance",
     "무료 1위 시세·뉴스",
     "무료 시세·차트·뉴스 원스톱. 개인 1순위 무료 대시보드.",
     "무료+유료", "https://finance.yahoo.com"),
    ("News / Wire", "Benzinga Pro",
     "트레이더 전용 속보·스캐너·알림",
     "트레이더용 속보 피드. 레이더 스캐너 결합.",
     "유료", "https://www.benzinga.com/pro"),
    ("News / Wire", "Fly on the Wall",
     "애널리스트 Upgrade/Downgrade 집계",
     "애널리스트 액션 집계 — 아침 체크 필수.",
     "유료", "https://theflyonthewall.com"),
    ("News / Wire", "Street Insider",
     "프로 트레이더용 속보·인사이더",
     "Fly 대안, 애널·인사이더·M&A 속보.",
     "유료", "https://www.streetinsider.com"),
    ("News / Wire", "Investor's Business Daily (IBD)",
     "성장주·CAN SLIM 방식",
     "오닐 성장주 스타일.",
     "유료", "https://www.investors.com"),
    ("News / Wire", "Zerohedge",
     "컨트래리언·매크로 블로그",
     "매크로 회의론·지정학. 편향 주의.",
     "무료+유료", "https://www.zerohedge.com"),

    # 5. SEC Filings / Fundamentals (raw)
    ("SEC Filings", "SEC EDGAR",
     "공식 SEC 제출 서류 무료",
     "10-K·10-Q·8-K·13F 1차 소스. 모든 미국 퀀트 출발점.",
     "무료(API 무료)", "https://www.sec.gov/edgar"),
    ("SEC Filings", "WhaleWisdom",
     "13F 헤지펀드 포트폴리오 추적",
     "분기 13F 집계. 스마트머니 포지셔닝.",
     "무료+유료", "https://whalewisdom.com"),
    ("SEC Filings", "OpenInsider",
     "내부자 매매 집계",
     "경영진 매수·매도 트래킹.",
     "무료", "http://openinsider.com"),
    ("SEC Filings", "Insider Monkey",
     "헤지펀드 13F + 아티클",
     "헤지펀드 분석·아티클.",
     "무료+유료", "https://www.insidermonkey.com"),

    # 6. Options / Flow Data
    ("Options / Flow", "Unusual Whales",
     "옵션 플로우 1위, 정치인 매매 추적",
     "비정상 옵션 플로우·다크풀. 스마트머니 옵션 포지션 모니터.",
     "유료", "https://unusualwhales.com"),
    ("Options / Flow", "Cheddar Flow",
     "옵션 플로우 대안",
     "UW 대체·검증.",
     "유료", "https://www.cheddarflow.com"),
    ("Options / Flow", "Flowalgo",
     "옵션 flow 실시간",
     "옵션 flow 트레이더.",
     "유료", "https://www.flowalgo.com"),
    ("Options / Flow", "Market Chameleon",
     "옵션 스캐너·IV·스킬",
     "옵션 볼상대가치 스캐너.",
     "무료+유료", "https://marketchameleon.com"),
    ("Options / Flow", "OptionStrat",
     "옵션 전략 시각화",
     "스프레드 P&L 시각화.",
     "무료+유료", "https://optionstrat.com"),
    ("Options / Flow", "SqueezeMetrics (DIX/GEX)",
     "다크풀·감마익스포저 지표",
     "옵션 딜러 감마 포지셔닝 추적.",
     "무료+유료", "https://squeezemetrics.com"),
    ("Options / Flow", "CBOE",
     "옵션 거래소 공식 데이터",
     "VIX·SKEW·PUT/CALL 원본.",
     "무료+유료", "https://www.cboe.com"),

    # 7. Scanner / Screener
    ("Scanner / Screener", "Finviz Screener",
     "무료 펀더·테크 스크리너 1위",
     "재무+기술 조합 스크리닝. 매일 종목 발굴 무료.",
     "무료+유료", "https://finviz.com/screener.ashx"),
    ("Scanner / Screener", "Trade Ideas",
     "AI 실시간 스캐너 (이미 기재)",
     "AI 패턴 감지.",
     "유료", "https://www.trade-ideas.com"),
    ("Scanner / Screener", "Stock Rover",
     "장기투자 펀더멘털 스크리너",
     "장기 가치·배당 스크리너.",
     "유료", "https://www.stockrover.com"),
    ("Scanner / Screener", "Chartmill",
     "유럽·미국 테크니컬 스크리너",
     "기술적 스크리너 대안.",
     "무료+유료", "https://www.chartmill.com"),
    ("Scanner / Screener", "StockFetcher",
     "커스텀 스크리너 SQL-like",
     "세밀한 조건 조합.",
     "무료+유료", "https://www.stockfetcher.com"),

    # 8. Community / Forums
    ("Community / Forums", "Reddit r/stocks",
     "가장 큰 주식 서브",
     "일반 투자 질문·종목 토론.",
     "무료", "https://www.reddit.com/r/stocks"),
    ("Community / Forums", "Reddit r/investing",
     "장기투자 중심",
     "패시브·장기 포트.",
     "무료", "https://www.reddit.com/r/investing"),
    ("Community / Forums", "Reddit r/wallstreetbets",
     "밈스톡·옵션 투기 문화",
     "단기·투기·밈주 여론.",
     "무료", "https://www.reddit.com/r/wallstreetbets"),
    ("Community / Forums", "Reddit r/valueinvesting",
     "가치투자자 커뮤니티",
     "가치투자 thesis·Buffett 스타일.",
     "무료", "https://www.reddit.com/r/valueinvesting"),
    ("Community / Forums", "Reddit r/SecurityAnalysis",
     "그레이엄식 정통 가치투자",
     "10-K 심층 분석·DCF.",
     "무료", "https://www.reddit.com/r/SecurityAnalysis"),
    ("Community / Forums", "Reddit r/options",
     "옵션 전략 토론",
     "옵션 교육·전략 공유.",
     "무료", "https://www.reddit.com/r/options"),
    ("Community / Forums", "Reddit r/thetagang",
     "세타 숏 프리미엄 파는 커뮤니티",
     "CSP·Covered call 중심.",
     "무료", "https://www.reddit.com/r/thetagang"),
    ("Community / Forums", "Reddit r/Bogleheads",
     "인덱스 장기투자 본산",
     "3-fund portfolio·인덱스.",
     "무료", "https://www.reddit.com/r/Bogleheads"),
    ("Community / Forums", "Stocktwits",
     "트위터+종목 소셜 플랫폼",
     "종목별 실시간 센티먼트. 단타 트레이더 여론.",
     "무료+유료", "https://stocktwits.com"),
    ("Community / Forums", "Value Investors Club (VIC)",
     "초대제 가치투자자 클럽",
     "깊이 있는 thesis. 90일 대기.",
     "무료(초대)", "https://www.valueinvestorsclub.com"),
    ("Community / Forums", "Corner of Berkshire & Fairfax",
     "버크셔·Fairfax 팬 포럼",
     "장기 가치 커뮤니티.",
     "무료", "https://www.cornerofberkshireandfairfax.ca"),
    ("Community / Forums", "Bogleheads Forum",
     "Jack Bogle 패시브 투자 본산",
     "ETF·인덱스·세금 최적화.",
     "무료", "https://www.bogleheads.org"),

    # 9. Discord / Chat
    ("Discord / Chat", "Atlas Trading Discord",
     "데이 트레이더 커뮤니티",
     "단타·갭·모멘텀.",
     "유료", "https://atlastrading.com"),
    ("Discord / Chat", "Investors Underground (IU)",
     "Nate Michaud 데이트레이딩 커뮤니티",
     "스캠·플러머 추적·데이트레이더 멘토.",
     "유료", "https://www.investorsunderground.com"),
    ("Discord / Chat", "Bullish Bears",
     "교육 중심 커뮤니티",
     "초중급 데이트레이더 교육.",
     "유료", "https://bullishbears.com"),
    ("Discord / Chat", "Jason Bond Picks",
     "스윙트레이딩 픽 서비스 (평판 혼재)",
     "스윙 픽·알림.",
     "유료(주의)", "https://jasonbondpicks.com"),
    ("Discord / Chat", "DumbMoney (WSB 영화 커뮤니티)",
     "밈스톡 추적 커뮤니티",
     "밈스톡 센티먼트.",
     "무료+유료", "-"),

    # 10. Twitter / X (FinTwit)
    ("FinTwit (X)", "@unusual_whales",
     "옵션 플로우·정치인 매매 알림",
     "실시간 옵션 스윕·정치인 13F.",
     "무료+유료", "https://twitter.com/unusual_whales"),
    ("FinTwit (X)", "@zerohedge",
     "컨트래리언 매크로 계정",
     "회의론·지정학. 편향 주의.",
     "무료", "https://twitter.com/zerohedge"),
    ("FinTwit (X)", "@FirstSquawk",
     "브레이킹 뉴스·헤드라인",
     "장중 속보 아카이브.",
     "무료+유료", "https://twitter.com/FirstSquawk"),
    ("FinTwit (X)", "@LizAnnSonders (Schwab)",
     "시장·매크로 차트",
     "매크로 데이터 비주얼라이제이션.",
     "무료", "https://twitter.com/LizAnnSonders"),
    ("FinTwit (X)", "@elerianm (El-Erian)",
     "매크로·중앙은행",
     "연준·ECB 해설.",
     "무료", "https://twitter.com/elerianm"),
    ("FinTwit (X)", "@CharlieBilello",
     "시장 통계·차트",
     "시장 역사 비교 차트.",
     "무료", "https://twitter.com/charliebilello"),
    ("FinTwit (X)", "@HumbleStudent (Cam Hui)",
     "기술적·매크로 로직",
     "기술·섹터 로테이션.",
     "무료", "https://twitter.com/HumbleStudent"),
    ("FinTwit (X)", "@TheLastBearSta1",
     "베어 thesis 큐레이션",
     "베어 thesis 아이디어.",
     "무료", "https://twitter.com/TheLastBearSta1"),
    ("FinTwit (X)", "@jimcramer",
     "CNBC Mad Money 호스트",
     "(콘트래리언 지표로 활용)",
     "무료", "https://twitter.com/jimcramer"),

    # 11. Newsletters
    ("Newsletters", "Matt Levine's Money Stuff (Bloomberg)",
     "금융계 최고 인기 무료 뉴스레터",
     "매일 금융·규제·M&A 이슈 해설. 무료.",
     "무료", "https://www.bloomberg.com/account/newsletters/money-stuff"),
    ("Newsletters", "Stratechery (Ben Thompson)",
     "Tech 전략 분석",
     "테크 기업 전략. 무료 주1회 + 유료.",
     "무료+유료", "https://stratechery.com"),
    ("Newsletters", "The Daily Shot (Bloomberg/WSJ)",
     "매일 차트로 보는 매크로",
     "매크로 차트북.",
     "유료", "https://dailyshotbrief.com"),
    ("Newsletters", "The Transcript",
     "어닝콜 발췌 주간",
     "CEO 발언 모음. 산업 트렌드.",
     "무료+유료", "https://thetranscript.substack.com"),
    ("Newsletters", "Net Interest (Marc Rubinstein)",
     "금융산업 깊이",
     "금융·보험·핀테크 분석.",
     "무료+유료", "https://www.netinterest.co"),
    ("Newsletters", "Morning Brew",
     "일반인 친화 비즈니스 뉴스",
     "가벼운 아침 브리핑.",
     "무료", "https://www.morningbrew.com"),
    ("Newsletters", "The Daily Upside",
     "금융·비즈니스 깊이",
     "중간 수준 분석·일일.",
     "무료", "https://www.thedailyupside.com"),
    ("Newsletters", "Not Boring (Packy McCormick)",
     "테크·벤처·스타트업",
     "성장주·테크 thesis.",
     "무료+유료", "https://www.notboring.co"),
    ("Newsletters", "The Diff (Byrne Hobart)",
     "비즈·금융·테크 깊이",
     "산업 구조 분석.",
     "무료+유료", "https://www.thediff.co"),
    ("Newsletters", "Pomp Letter (Anthony Pompliano)",
     "매크로·크립토",
     "크립토·매크로 혼합.",
     "무료+유료", "https://pomp.substack.com"),

    # 12. Podcasts
    ("Podcasts", "We Study Billionaires (TIP)",
     "가치투자·빌리어네어 연구",
     "버핏·엠그라햄 학습.",
     "무료", "https://www.theinvestorspodcast.com"),
    ("Podcasts", "Chat with Traders",
     "인터뷰: 프로 트레이더",
     "실전 트레이더 인터뷰.",
     "무료", "https://chatwithtraders.com"),
    ("Podcasts", "Invest Like the Best (Patrick O'Shaughnessy)",
     "CEO·펀드매니저 인터뷰",
     "장기 관점·비즈니스 품질.",
     "무료", "https://joincolossus.com/episodes"),
    ("Podcasts", "Acquired",
     "테크 대기업 역사·전략",
     "기업 역사·M&A 심층.",
     "무료", "https://www.acquired.fm"),
    ("Podcasts", "All-In Podcast",
     "VC 4인방: Chamath·Sacks 등",
     "테크·정치·매크로 잡담 + 인사이트.",
     "무료", "https://www.allinpodcast.co"),
    ("Podcasts", "Bloomberg Surveillance",
     "BB TV 아침 매크로",
     "아침 매크로·중앙은행.",
     "무료", "https://www.bloomberg.com/surveillance"),
    ("Podcasts", "Odd Lots (Bloomberg)",
     "금융 구석진 주제 딥다이브",
     "크레딧·상품·특수주제.",
     "무료", "https://www.bloomberg.com/oddlots"),
    ("Podcasts", "Masters in Business (Barry Ritholtz)",
     "RIA 업계·매크로 인터뷰",
     "주간 심층 인터뷰.",
     "무료", "https://ritholtz.com/category/podcast"),
    ("Podcasts", "Planet Money (NPR)",
     "경제를 대중 언어로",
     "매크로 입문·스토리.",
     "무료", "https://www.npr.org/sections/money"),

    # 13. Economic Data / Macro
    ("Economic Data / Macro", "FRED (St. Louis Fed)",
     "매크로 데이터 성경 — 무료 모든 시계열",
     "GDP·CPI·고용·금리·통화·크레딧. 미국 매크로 1순위.",
     "무료(API 무료)", "https://fred.stlouisfed.org"),
    ("Economic Data / Macro", "BLS (Bureau of Labor Statistics)",
     "고용·임금·CPI 원본",
     "Nonfarm payroll·CPI 발표 1차.",
     "무료", "https://www.bls.gov"),
    ("Economic Data / Macro", "BEA (Bureau of Economic Analysis)",
     "GDP·개인소비·무역수지",
     "GDP 분기 발표·PCE 물가.",
     "무료", "https://www.bea.gov"),
    ("Economic Data / Macro", "U.S. Treasury",
     "국채 발행·수익률 공식",
     "Treasury 공식 금리·발행 일정.",
     "무료", "https://home.treasury.gov"),
    ("Economic Data / Macro", "CME FedWatch",
     "연준 금리 인상/인하 확률",
     "Fed Funds 선물 imply 확률. 모든 프로 체크.",
     "무료", "https://www.cmegroup.com/trading/interest-rates/countdown-to-fomc.html"),
    ("Economic Data / Macro", "ISM",
     "제조업·서비스 PMI",
     "월간 PMI 경기 선행지표.",
     "유료(요약 무료)", "https://www.ismworld.org"),
    ("Economic Data / Macro", "Atlanta Fed GDPNow",
     "실시간 GDP 추정",
     "연준 지부 GDP 실시간 업데이트.",
     "무료", "https://www.atlantafed.org/cqer/research/gdpnow"),
    ("Economic Data / Macro", "Conference Board",
     "소비자신뢰지수·LEI",
     "월간 경기선행지수.",
     "무료+유료", "https://www.conference-board.org"),
    ("Economic Data / Macro", "Earnings Whispers",
     "실적 예상치 + 어닝 위스퍼",
     "실적 시즌 공식+언오피셜 컨센서스.",
     "무료+유료", "https://www.earningswhispers.com"),
    ("Economic Data / Macro", "Forex Factory",
     "경제캘린더 표준 (FX 트레이더)",
     "매크로 이벤트 캘린더·중요도 표기.",
     "무료", "https://www.forexfactory.com"),
    ("Economic Data / Macro", "Investing.com Calendar",
     "무료 경제캘린더·실적캘린더",
     "전 종목·전 시장 캘린더 무료.",
     "무료+유료", "https://www.investing.com/economic-calendar"),
    ("Economic Data / Macro", "Zacks",
     "어닝 컨센서스 + 랭킹",
     "Zacks Rank 모멘텀·어닝.",
     "무료+유료", "https://www.zacks.com"),

    # 14. Data APIs (Dev)
    ("Data APIs (Dev)", "Polygon.io",
     "실시간 + 과거 시세 API",
     "프로·세미프로 퀀트. 실시간 US 주식·옵션·선물·FX.",
     "유료(무료 티어 있음)", "https://polygon.io"),
    ("Data APIs (Dev)", "IEX Cloud (Deprecated 2024)",
     "저가 프로 API — 서비스 종료",
     "(참고: IEX Cloud 2024년 종료됨. 대체 Polygon/Finnhub.)",
     "종료", "https://iexcloud.io"),
    ("Data APIs (Dev)", "Alpha Vantage",
     "무료 티어 API",
     "25 req/day 무료. 프로토타입용.",
     "무료+유료", "https://www.alphavantage.co"),
    ("Data APIs (Dev)", "Finnhub",
     "글로벌 API + 뉴스",
     "60 req/min 무료. 글로벌 커버리지.",
     "무료+유료", "https://finnhub.io"),
    ("Data APIs (Dev)", "Twelve Data",
     "다기간 API",
     "주식·FX·암호화폐 혼합.",
     "무료+유료", "https://twelvedata.com"),
    ("Data APIs (Dev)", "Financial Modeling Prep",
     "재무·실적·M&A API",
     "재무 API 저가.",
     "무료+유료", "https://site.financialmodelingprep.com"),
    ("Data APIs (Dev)", "EOD Historical Data",
     "일봉 과거 API",
     "백테스트 과거 데이터.",
     "유료", "https://eodhistoricaldata.com"),
    ("Data APIs (Dev)", "Nasdaq Data Link (ex-Quandl)",
     "프리미엄 데이터셋",
     "대체 데이터·프리미엄 셋.",
     "유료(일부 무료)", "https://data.nasdaq.com"),
    ("Data APIs (Dev)", "yfinance (Python)",
     "Yahoo Finance 비공식 Python",
     "무료지만 TOS 회색·rate limit. 프로토타입 1순위.",
     "무료(오픈소스)", "https://github.com/ranaroussi/yfinance"),
    ("Data APIs (Dev)", "Tiingo",
     "저가 프로 API",
     "펀더멘털+시세 저가.",
     "무료+유료", "https://www.tiingo.com"),

    # 15. Crypto-adjacent (pro hedging)
    ("Crypto / Hedge", "Coinbase Advanced Trade",
     "미국 주요 크립토 거래소",
     "달러 베이스 크립토 헷징.",
     "무료(계좌)", "https://www.coinbase.com"),
    ("Crypto / Hedge", "Kraken",
     "프로 유저 크립토 거래소",
     "파생·마진·스테이킹.",
     "무료(계좌)", "https://www.kraken.com"),
    ("Crypto / Hedge", "Glassnode",
     "온체인 데이터",
     "BTC·ETH 온체인 지표.",
     "무료+유료", "https://glassnode.com"),
    ("Crypto / Hedge", "Nansen",
     "온체인 스마트머니 추적",
     "지갑별 스마트머니 플로우.",
     "유료", "https://www.nansen.ai"),
]

# ───────────────────────────────────────────────────────────────────────
# Excel 빌드
# ───────────────────────────────────────────────────────────────────────
wb = Workbook()
wb.remove(wb.active)

HEADER_FILL = PatternFill("solid", start_color="1F4E78")
HEADER_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=11)
CAT_FONT = Font(name="Arial", bold=True, size=10, color="1F4E78")
BODY_FONT = Font(name="Arial", size=10)
LINK_FONT = Font(name="Arial", size=10, color="0563C1", underline="single")
THIN_BORDER = Border(
    left=Side(style="thin", color="D0D0D0"),
    right=Side(style="thin", color="D0D0D0"),
    top=Side(style="thin", color="D0D0D0"),
    bottom=Side(style="thin", color="D0D0D0"),
)

# 카테고리별 파스텔 색상
CAT_COLORS = [
    "EAF2FB", "FBF3E3", "E8F6EC", "FBEAEA", "F3EBFB",
    "FBF8E3", "E3F6F9", "FBEBF4", "EEF2E3", "F1EEFB",
    "FBF0E3", "E7F6FB", "FBE8F0", "EFFBE3", "E3E7FB",
    "FBFAE3", "E3FBF2", "FBE8E3", "F0FBE3", "E3EFFB",
]

def build_sheet(ws, rows, title_banner):
    # 상단 배너 (카테고리 A1에 제목)
    ws.row_dimensions[1].height = 28
    ws["A1"] = title_banner
    ws["A1"].font = Font(name="Arial", bold=True, size=14, color="FFFFFF")
    ws["A1"].fill = PatternFill("solid", start_color="1F4E78")
    ws["A1"].alignment = Alignment(horizontal="left", vertical="center", indent=1)
    ws.merge_cells("A1:G1")

    headers = ["번호", "카테고리", "플랫폼", "핵심 기능", "상황별 사용법", "유료/무료", "링크"]
    for col, h in enumerate(headers, 1):
        c = ws.cell(row=2, column=col, value=h)
        c.font = HEADER_FONT
        c.fill = HEADER_FILL
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        c.border = THIN_BORDER
    ws.row_dimensions[2].height = 30

    # 카테고리별 색 할당
    cat_to_color = {}
    idx = 0
    for cat, *_ in rows:
        if cat not in cat_to_color:
            cat_to_color[cat] = CAT_COLORS[idx % len(CAT_COLORS)]
            idx += 1

    for i, (cat, name, func, usecase, price, link) in enumerate(rows, start=1):
        r = i + 2  # row 1=배너, row 2=헤더
        color = cat_to_color[cat]
        fill = PatternFill("solid", start_color=color)

        values = [i, cat, name, func, usecase, price, link]
        for col, val in enumerate(values, 1):
            c = ws.cell(row=r, column=col, value=val)
            c.fill = fill
            c.border = THIN_BORDER
            c.alignment = Alignment(vertical="top", wrap_text=True)
            if col == 1:
                c.font = BODY_FONT
                c.alignment = Alignment(horizontal="center", vertical="top")
            elif col == 2:
                c.font = CAT_FONT
            elif col == 7:
                c.font = LINK_FONT
                if val and val.startswith("http"):
                    c.hyperlink = val
            else:
                c.font = BODY_FONT

    # 열 너비
    widths = {1: 6, 2: 20, 3: 34, 4: 44, 5: 60, 6: 16, 7: 46}
    for col, w in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = w

    # 행 높이 자동 처리 대신 최소 40으로 지정해 가독성 확보
    for r in range(3, len(rows) + 3):
        ws.row_dimensions[r].height = 48

    ws.freeze_panes = "A3"
    ws.auto_filter.ref = f"A2:G{len(rows)+2}"

kr_ws = wb.create_sheet("한국 플랫폼")
build_sheet(kr_ws, KR, "🇰🇷 한국 전업투자자 플랫폼 — 카테고리별 풀 스택")

us_ws = wb.create_sheet("미국 플랫폼")
build_sheet(us_ws, US, "🇺🇸 US Pro Trader Platforms — Category-by-Category Full Stack")

# 시트 3: 매핑 — 우리 플랫폼이 각 기능을 어떻게 커버해야 하는지
map_ws = wb.create_sheet("플랫폼 기능 매핑")
map_ws.row_dimensions[1].height = 28
map_ws["A1"] = "📋 우리 플랫폼 기능 매핑 — 한·미 벤치마크 → Stock Terminal 구현 우선순위"
map_ws["A1"].font = Font(name="Arial", bold=True, size=14, color="FFFFFF")
map_ws["A1"].fill = PatternFill("solid", start_color="1F4E78")
map_ws["A1"].alignment = Alignment(horizontal="left", vertical="center", indent=1)
map_ws.merge_cells("A1:E1")

map_headers = ["기능 카테고리", "한국 벤치마크", "미국 벤치마크", "Stock Terminal 현재 상태", "다음 액션 (우선순위)"]
for col, h in enumerate(map_headers, 1):
    c = map_ws.cell(row=2, column=col, value=h)
    c.font = HEADER_FONT
    c.fill = HEADER_FILL
    c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    c.border = THIN_BORDER
map_ws.row_dimensions[2].height = 30

mapping_rows = [
    ("실시간 시세 (국내)", "네이버 증권 · 키움 영웅문", "—", "✅ 구현 (KIS 실시간 API 연동)", "P2 · 장중 실시간 검증"),
    ("실시간 시세 (해외)", "토스증권·미래에셋 해외주식", "TradingView · Yahoo Finance", "❌ 없음", "P0 · 미국 지수·환율·VIX 매크로 카드 먼저"),
    ("공시", "DART · KIND", "SEC EDGAR · Whalewisdom", "🟡 DART 부분 연동 (W2.6 탭만)", "P1 · 홈 TodayDisclosures 붙이기 (이미 컴포넌트 있음)"),
    ("뉴스·속보", "한경·매경·인포맥스", "WSJ · Bloomberg · Benzinga", "🟡 Google News RSS 탭만", "P1 · 홈 TodayNews 붙이기"),
    ("커뮤니티·채팅", "네이버 토론실 · 디씨 주갤", "Reddit · Stocktwits · Discord", "✅ 전체 채팅 구현", "P2 · 종목 상세 단위 채팅 유도"),
    ("차트·기술분석", "TradingView · Investar", "TradingView · thinkorswim · Finviz", "🟡 TradingView 위젯 부분", "P2 · 종목 상세 차트 강화"),
    ("스크리너", "네이버 스크리너 · 퀀트킹", "Finviz · Trade Ideas", "✅ /screener 구현", "P2 · 필터 확장"),
    ("펀더멘털·재무", "FnGuide · 한경컨센서스", "Stock Analysis · Koyfin · Macrotrends", "✅ W2.3 재무 탭", "P3 · 컨센서스·10년 히스토리"),
    ("실적 캘린더", "FnGuide · 컨센서스", "Earnings Whispers · Zacks", "❌ 더미 (#38)", "P1 · DART 공시 기반 예정 실적"),
    ("경제 캘린더", "한은 ECOS", "Investing.com · Forex Factory", "❌ 더미 (#39)", "P1 · ECOS 지표 발표일정"),
    ("관심종목", "네이버 관심주 · HTS", "Yahoo Finance · Koyfin", "✅ WatchlistLive 구현", "P3 · 드래그 정렬"),
    ("수급 (외국인·기관)", "KRX · HTS 수급", "(없음, 13F 월단위)", "✅ InstitutionalFlow 구현", "P3 · 정교화"),
    ("거래량·급등", "각 HTS", "Finviz · Benzinga Pro", "✅ VolumeSpike 구현", "P3"),
    ("글로벌 지수", "미래에셋·키움 해외", "Yahoo · Bloomberg", "🟡 GlobalFutures (더미 가능성)", "P0 · 실데이터 연결"),
    ("매크로 (환율·금리·VIX)", "인포맥스 · 한은 ECOS", "FRED · CME FedWatch", "❌ 없음", "P0 · 새 Row 필요"),
    ("섹터 로테이션", "각 HTS 업종", "Finviz heatmap · StockCharts RRG", "❌ 없음", "P1 · 업종 등락률 카드"),
    ("투자경고·관리", "KIND 시장조치", "SEC halts", "🟡 WarningStocks (더미)", "P1 · KRX 시장조치 연결"),
    ("TopMovers 상승/하락", "네이버·각 HTS", "Finviz · Yahoo", "🟡 TopMovers.tsx 만들어두고 미사용", "P1 · 홈에 붙이기 (무료 수확)"),
    ("파트너 Lead Gen", "(없음 — 본 모델 독창)", "Investopedia affiliate, NerdWallet", "✅ W4 Phase 2 완성", "수익 모델 실행"),
]

for i, (a, b, c_, d, e) in enumerate(mapping_rows, start=3):
    color = CAT_COLORS[(i - 3) % len(CAT_COLORS)]
    fill = PatternFill("solid", start_color=color)
    for col, val in enumerate([a, b, c_, d, e], 1):
        c = map_ws.cell(row=i, column=col, value=val)
        c.fill = fill
        c.border = THIN_BORDER
        c.alignment = Alignment(vertical="top", wrap_text=True)
        c.font = BODY_FONT if col != 1 else CAT_FONT
    map_ws.row_dimensions[i].height = 44

for col, w in {1: 24, 2: 30, 3: 38, 4: 36, 5: 40}.items():
    map_ws.column_dimensions[get_column_letter(col)].width = w

map_ws.freeze_panes = "A3"
map_ws.auto_filter.ref = f"A2:E{len(mapping_rows)+2}"

output = "/sessions/admiring-modest-johnson/mnt/OTMarketing/research/전업투자자_플랫폼_리스트.xlsx"
wb.save(output)
print(f"SAVED: {output}")
print(f"KR rows: {len(KR)}")
print(f"US rows: {len(US)}")
print(f"Mapping rows: {len(mapping_rows)}")
